In [114]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [72]:
df=pd.read_csv('datos_limpios.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8519 entries, 0 to 8518
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8519 non-null   object
 1   Item_Weight                8519 non-null   float64
 2   Item_Fat_Content           8519 non-null   object
 3   Item_Visibility            8519 non-null   float64
 4   Item_Type                  8519 non-null   object
 5   Item_MRP                   8519 non-null   float64
 6   Outlet_Identifier          8519 non-null   object
 7   Outlet_Establishment_Year  8519 non-null   int64
 8   Outlet_Size                8519 non-null   object
 9   Outlet_Location_Type       8519 non-null   object
 10  Outlet_Type                8519 non-null   object
 11  Item_Outlet_Sales          8519 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 798.8+ KB

# Convertir variables categóricas a numéricas.

## 1. Item_Identifier

In [73]:
item_id = np.unique(df['Item_Identifier'])
gle = LabelEncoder()
itemid_labels = gle.fit_transform(df['Item_Identifier'])
itemid_mappings = {index: label for index, label in 
                  enumerate(gle.classes_)}
df['Item_Identifier'] =itemid_labels
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,156,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,8,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,660,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,1117,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800
4,1293,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

## 2. Item_Fat_Content

In [74]:
df['Item_Fat_Content']=df['Item_Fat_Content'].replace(['Low Fat','Regular'],[1,0])
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,156,9.30,1,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,8,5.92,0,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,660,17.50,1,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,1117,19.20,0,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800
4,1293,8.93,1,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

## 3. Item_Type

In [75]:
# transform and map
gen_le = LabelEncoder()
gen_labels = gen_le.fit_transform(df[['Item_Type']])
df['Item_Type_Label'] = gen_labels

# encode labels using one-hot encoding scheme
gen_ohe = OneHotEncoder()
gen_feature_arr = gen_ohe.fit_transform(
                              df[['Item_Type']]).toarray()
gen_feature_labels = list(gen_le.classes_)
gen_features = pd.DataFrame(gen_feature_arr, 
                            columns=gen_feature_labels)
gen_features

C:\Users\Paula.Lillo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,Fruits and Vegetables,Hard Drinks,Health and Hygiene,Household,Meat,Others,Seafood,Snack Foods,Soft Drinks,Starchy Foods
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8515,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8516,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8517,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8518,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [76]:
df_1 = pd.concat([df, gen_features], axis=1)
df_1

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,...,Fruits and Vegetables,Hard Drinks,Health and Hygiene,Household,Meat,Others,Seafood,Snack Foods,Soft Drinks,Starchy Foods
0,156,9.300,1,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,8,5.920,0,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,660,17.500,1,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1117,19.200,0,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1293,8.930,1,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8514,369,6.865,1,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8515,893,8.380,0,0.046982,Baking Goods,108.1570,OUT045,2002,S/I,Tier 2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8516,1353,10.600,1,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8517,679,7.210,0,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8518,50,14.800,1,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## 4. Outlet_Identifier

In [77]:
# transform and map
gen_le = LabelEncoder()
gen_labels = gen_le.fit_transform(df[['Outlet_Identifier']])
df_1['Outlet_Identifier_Label'] = gen_labels

# encode labels using one-hot encoding scheme
gen_ohe = OneHotEncoder()
gen_feature_arr = gen_ohe.fit_transform(
                              df[['Outlet_Identifier']]).toarray()
gen_feature_labels = list(gen_le.classes_)
gen_features = pd.DataFrame(gen_feature_arr, 
                            columns=gen_feature_labels)
df_1 = pd.concat([df_1, gen_features], axis=1)
df_1

C:\Users\Paula.Lillo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,...,OUT010,OUT013,OUT017,OUT018,OUT019,OUT027,OUT035,OUT045,OUT046,OUT049
0,156,9.300,1,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,8,5.920,0,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,660,17.500,1,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1117,19.200,0,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1293,8.930,1,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8514,369,6.865,1,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8515,893,8.380,0,0.046982,Baking Goods,108.1570,OUT045,2002,S/I,Tier 2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8516,1353,10.600,1,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8517,679,7.210,0,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8518,50,14.800,1,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## 5. Outlet_Size

In [78]:
df_1['Outlet_Size'].value_counts()

Small     2942
Medium    2790
S/I       1855
High       932
Name: Outlet_Size, dtype: int64

In [86]:
df_1['Outlet_Size']=df_1['Outlet_Size'].replace(['Small','Medium','High','S/I'],[1,2,3,0])
df_1

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,...,OUT010,OUT013,OUT017,OUT018,OUT019,OUT027,OUT035,OUT045,OUT046,OUT049
0,156,9.300,1,0.016047,Dairy,249.8092,OUT049,1999,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,8,5.920,0,0.019278,Soft Drinks,48.2692,OUT018,2009,2,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,660,17.500,1,0.016760,Meat,141.6180,OUT049,1999,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1117,19.200,0,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,1,3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1293,8.930,1,0.000000,Household,53.8614,OUT013,1987,3,3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8514,369,6.865,1,0.056783,Snack Foods,214.5218,OUT013,1987,3,3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8515,893,8.380,0,0.046982,Baking Goods,108.1570,OUT045,2002,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8516,1353,10.600,1,0.035186,Health and Hygiene,85.1224,OUT035,2004,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8517,679,7.210,0,0.145221,Snack Foods,103.1332,OUT018,2009,2,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8518,50,14.800,1,0.044878,Soft Drinks,75.4670,OUT046,1997,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## 6. Outlet_Location_Type

In [80]:
df_1['Outlet_Location_Type'].value_counts()

Tier 3    3347
Tier 2    2785
Tier 1    2387
Name: Outlet_Location_Type, dtype: int64

In [81]:
df_1['Outlet_Location_Type']=df_1['Outlet_Location_Type'].replace(['Tier 1','Tier 2','Tier 3'],[1,2,3])
df_1.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,...,OUT010,OUT013,OUT017,OUT018,OUT019,OUT027,OUT035,OUT045,OUT046,OUT049
0,156,9.30,1,0.016047,Dairy,249.8092,OUT049,1999,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,8,5.92,0,0.019278,Soft Drinks,48.2692,OUT018,2009,2,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,660,17.50,1,0.016760,Meat,141.6180,OUT049,1999,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1117,19.20,0,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,1,3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1293,8.93,1,0.000000,Household,53.8614,OUT013,1987,High,3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 7. Outlet_Type

In [82]:
df_1['Outlet_Type'].value_counts()

Supermarket Type1    5577
Grocery Store        1082
Supermarket Type3     932
Supermarket Type2     928
Name: Outlet_Type, dtype: int64

In [91]:
df_1['Outlet_Type']=df_1['Outlet_Type'].replace(['Supermarket Type1','Supermarket Type2','Supermarket Type3','Grocery Store'],[1,2,3,0])

## Mapa de correlaciones.

In [92]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8519 entries, 0 to 8518
Data columns (total 40 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8519 non-null   int32
 1   Item_Weight                8519 non-null   float64
 2   Item_Fat_Content           8519 non-null   int64
 3   Item_Visibility            8519 non-null   float64
 4   Item_Type                  8519 non-null   object
 5   Item_MRP                   8519 non-null   float64
 6   Outlet_Identifier          8519 non-null   object
 7   Outlet_Establishment_Year  8519 non-null   int64
 8   Outlet_Size                8519 non-null   int64
 9   Outlet_Location_Type       8519 non-null   int64
 10  Outlet_Type                8519 non-null   int64
 11  Item_Outlet_Sales          8519 non-null   float64
 12  Item_Type_Label            8519 non-null   int32
 13  Baking Goods               8519 non-null   float64
 14  Breads                     8519 non-null   float64
 15  Breakfast                  8519 non-null   float64
 16  Canned                     8519 non-null   float64
 17  Dairy                      8519 non-null   float64
 18  Frozen Foods               8519 non-null   float64
 19  Fruits and Vegetables      8519 non-null   float64
 20  Hard Drinks                8519 non-null   float64
 21  Health and Hygiene         8519 non-null   float64
 22  Household                  8519 non-null   float64
 23  Meat                       8519 non-null   float64
 24  Others                     8519 non-null   float64
 25  Seafood                    8519 non-null   float64
 26  Snack Foods                8519 non-null   float64
 27  Soft Drinks                8519 non-null   float64
 28  Starchy Foods              8519 non-null   float64
 29  Outlet_Identifier_Label    8519 non-null   int32
 30  OUT010                     8519 non-null   float64
 31  OUT013                     8519 non-null   float64
 32  OUT017                     8519 non-null   float64
 33  OUT018                     8519 non-null   float64
 34  OUT019                     8519 non-null   float64
 35  OUT027                     8519 non-null   float64
 36  OUT035                     8519 non-null   float64
 37  OUT045                     8519 non-null   float64
 38  OUT046                     8519 non-null   float64
 39  OUT049                     8519 non-null   float64
dtypes: float64(30), int32(3), int64(5), object(2)
memory usage: 2.5+ MB

In [93]:
corr=df_1.corr()
corr.style.background_gradient(cmap='coolwarm').set_precision(2)

# Linear Regression

In [99]:
X = df_1.drop(['Item_Outlet_Sales','Item_Type_Label','Item_Type','Outlet_Identifier','Outlet_Identifier_Label'],axis=1)
Y=df_1['Item_Outlet_Sales']

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.3, random_state=42)
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [107]:
y_pred=lin_reg.predict(X_test)
r2_score(y_test, y_pred)

0.5624795765959398

In [111]:
reg.coef_

array([ 4.40616374e-02,  9.37273595e-02, -3.88972987e+01, -3.06322766e+02,
        1.55634785e+01,  1.51970940e+01,  2.51824959e+02,  7.94937524e+01,
       -2.16114022e+02, -6.90482136e+00, -9.37267787e+00,  3.98122381e+00,
        2.27145525e+01, -3.99118012e+01, -2.78467797e+01,  2.55789240e+01,
        2.13445891e+01, -4.83589935e+01, -7.52040243e+01, -8.83229244e+00,
       -5.82183672e+01,  1.90754471e+02, -1.84481603e+01, -3.50066294e+00,
        3.22248207e+01, -1.68126694e+03, -8.06585156e+01,  5.23668601e+02,
       -4.71362957e+02, -1.30693876e+03,  1.61953135e+03,  3.57571732e+02,
        4.25767552e+02,  3.99278192e+02,  2.14409752e+02])

In [109]:
reg.intercept_

-30989.076866873023

In [124]:
X = df_1.drop(['Item_Outlet_Sales','Item_Type_Label','Item_Type','Outlet_Identifier','Outlet_Identifier_Label'],axis=1)
Y=df_1['Item_Outlet_Sales']

In [125]:
scaler = StandardScaler()
# Ajuste en X (asumiendo que tu matriz de características es una matriz NumPy)
scaler.fit(X)
# Transform X
scaler.transform(X)

array([[-1.38784312, -0.76959845,  0.73784568, ..., -0.3498541 ,
        -0.35006541,  2.85660901],
       [-1.71841608, -1.49713327, -1.35529696, ..., -0.3498541 ,
        -0.35006541, -0.35006541],
       [-0.26210819,  0.99542688,  0.73784568, ..., -0.3498541 ,
        -0.35006541,  2.85660901],
       ...,
       [ 1.28577734, -0.48977736,  0.73784568, ..., -0.3498541 ,
        -0.35006541, -0.35006541],
       [-0.21966977, -1.21946466, -1.35529696, ..., -0.3498541 ,
        -0.35006541, -0.35006541],
       [-1.62460484,  0.41426   ,  0.73784568, ..., -0.3498541 ,
         2.85660901, -0.35006541]])

In [126]:
scaler = StandardScaler()
neighbors = np.arange(1,200)
while (r2<=0.55):
    X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.2)    
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test) # Ojo: escalamiento de test se hace en base al train
    for i,k in enumerate(neighbors):
        knn = KNeighborsRegressor(n_neighbors=k)
        knn.fit(X_train, y_train)    
        y_pred=knn.predict(X_test)
        r2=r2_score(y_test, y_pred)
        if r2>0.55:
            break
    print(r2)
    print(k)

0.37664103200615495
199
0.3702748921669903
199
0.39785832489870043
199
0.3955657775347329
199
0.38698253239599634
199
0.38629884391675173
199
0.37379866629125846
199
0.3890391064377734
199
0.38342894298400443
199
0.3917783109655687
199
0.3970843671158828
199
0.3754431812089516
199
0.3801256751748152
199
0.3882476751877314
199
0.3957058958252213
199
0.37069384803256056
199
0.3796628116189976
199
0.4166064003073354
199
0.4021118681955457
199
0.37675776181321485
199
0.39887007162689425
199
0.3996192851288194
199
0.3773553687093709
199
0.3810536370559555
199
0.39143542625715755
199
0.3878667984144061
199
0.3860060050371511
199
0.37729525451802104
199
0.3945887167002705
199
0.38038601862964627
199
0.3867948969172219
199
0.38379358652076623
199
0.3646250164500141
199
0.3881794734364089
199
0.36551930613959116
199
0.37830695905122913
199
0.3848958167283473
199
0.37220786935984396
199
0.39906167024598904
199
0.38011842564391707
199
0.3633059864084095
199
0.3789517059542724
199
0.3732744637454132
199
0.39128420437760714
199
0.37723537461138956
199
0.37747506431615807
199
0.3861003714534711
199
0.3830334639373454
199
0.38591532804956896
199
0.3888637980663898
199
0.38753886302033935
199
0.3832795692331259
199
0.38189613603107486
199
0.4006080320629224
199
0.382312858399662
199
0.3801860533600303
199
0.3967057412452062
199
0.3806012081163157
199
0.3783322769678107
199
0.4033767094550037
199
0.3649160635757356
199
0.3902183093987416
199
0.3863064781767135
199
0.37143399846625813
199
0.38992553247290196
199
0.3871823272927608
199
0.3878292732547032
199
0.3923902170814021
199
0.3778256587068506
199
0.3907544703205591
199
0.3941298926419572
199
0.3675592859301333
199
0.3847288952661293
199
0.3865049508250823
199
0.37152853545131603
199
0.38628167598107344
199
0.39016001565812153
199
0.37379817270167437
199
0.39006259177875124
199
0.3636792580611625
199
0.3914631858868868
199
0.37550021657774046
199
0.3770637500285322
199
0.372324623537611
199
0.38235710891078223
199
0.41180965567584793
199
0.3950006608863065
199
0.41273418544483087
199
0.3835896445901015
199
0.3800427778700365
199
0.37618842702479593
199
0.3810257304653546
199
0.37943148637590607
199
0.382541823587511
199
0.37611745983175326
199
0.3715478062250738
199
0.37803368767175594
199
0.3790186553818876
199
0.3700004371286615
199
0.370447942214412
199
0.37819524986472464
199
0.37043208433759633
199
0.3661555326103527
199
0.3738057769755706
199
0.3773865597922045
199
0.3871541314353978
199
0.39289548538716246
199
0.37939273052513467
199
0.3634902133608855
199

KeyboardInterrupt: